/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PDAO.vistas;

import PDAO.Controldor.ControladorUser;
import PDAO.Modelo.Modelo;
import javax.swing.JOptionPane;

/**
 *
 * @author nahs1
 */
public class Ventana_Ingreso extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_Ingreso
     */
    ControladorUser x=new ControladorUser();
    public Ventana_Ingreso() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.   
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        JLblUsuario = new javax.swing.JLabel();
        JTxtUsuario = new javax.swing.JTextField();
        JLblContraseña = new javax.swing.JLabel();
        JPassword = new javax.swing.JPasswordField();
        JLblImagenIngreso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventana_Login");

        jPanel1.setLayout(null);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("INGRESAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(280, 310, 120, 23);

        JLblUsuario.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        JLblUsuario.setText("USUARIO:");
        JLblUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(JLblUsuario);
        JLblUsuario.setBounds(180, 190, 70, 30);
        jPanel1.add(JTxtUsuario);
        JTxtUsuario.setBounds(250, 190, 170, 20);

        JLblContraseña.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        JLblContraseña.setText("CONTRASEÑA:");
        jPanel1.add(JLblContraseña);
        JLblContraseña.setBounds(150, 260, 100, 14);

        JPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(JPassword);
        JPassword.setBounds(250, 250, 170, 20);

        JLblImagenIngreso.setBackground(new java.awt.Color(0, 0, 0));
        JLblImagenIngreso.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        JLblImagenIngreso.setForeground(new java.awt.Color(255, 255, 255));
        JLblImagenIngreso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/VentanaIngreso.png"))); // NOI18N
        jPanel1.add(JLblImagenIngreso);
        JLblImagenIngreso.setBounds(0, 0, 512, 441);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPasswordActionPerformed
        
    }//GEN-LAST:event_JPasswordActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        x.verificar(new Modelo(JTxtUsuario.getText(), JPassword.getText()));
                 // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Ingreso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLblContraseña;
    private javax.swing.JLabel JLblImagenIngreso;
    public javax.swing.JLabel JLblUsuario;
    public javax.swing.JPasswordField JPassword;
    public javax.swing.JTextField JTxtUsuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
