/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PDAO.vistas;

/**
 *
 * @author nahs1
 */

import Clases.cargar;
import javax.swing.JProgressBar;

public class Ventana_Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_Inicio
     */
    
    cargar hilo;
    
    public Ventana_Inicio() {
        initComponents();
        setTitle("Bienvenidos al Sistema");
        iniciar();
    }
    public void iniciar() {
        setLocationRelativeTo(null);
        hilo = new cargar(getBarraProgreso());
        hilo.start();
        hilo = null;
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelVentanaIncial = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BarraProgreso = new javax.swing.JProgressBar();
        JLblImagenInicial = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventana_Presentación_Inicial");

        JPanelVentanaIncial.setBackground(new java.awt.Color(204, 204, 204));
        JPanelVentanaIncial.setLayout(null);

        jLabel1.setText("GRUPO #1");
        JPanelVentanaIncial.add(jLabel1);
        jLabel1.setBounds(230, 460, 70, 16);

        BarraProgreso.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                BarraProgresoStateChanged(evt);
            }
        });
        JPanelVentanaIncial.add(BarraProgreso);
        BarraProgreso.setBounds(0, 451, 520, 39);

        JLblImagenInicial.setBackground(new java.awt.Color(0, 0, 0));
        JLblImagenInicial.setForeground(new java.awt.Color(255, 255, 255));
        JLblImagenInicial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ventana_Inicial.png"))); // NOI18N
        JPanelVentanaIncial.add(JLblImagenInicial);
        JLblImagenInicial.setBounds(0, 0, 512, 445);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelVentanaIncial, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelVentanaIncial, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BarraProgresoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_BarraProgresoStateChanged
        // TODO add your handling code here:
        if (BarraProgreso.getValue() == 100) {
            Ventana_Ingreso vi = new Ventana_Ingreso();
            vi.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_BarraProgresoStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar BarraProgreso;
    private javax.swing.JLabel JLblImagenInicial;
    private javax.swing.JPanel JPanelVentanaIncial;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables


    private JProgressBar getBarraProgreso() {
         return BarraProgreso;
    }
}
