/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PDAO.vistas;

import static DAO.MeseroDaoImpl1.id;
import static DAO.UsuarioDaoImpl.cargo;
import static DAO.UsuarioDaoImpl.codigo;
import static DAO.UsuarioDaoImpl.mesa;
import static DAO.pedidoDaoImpl.nom;
import static DAO.pedidoDaoImpl.pre;
import PDAO.Controldor.ControladoEstadistica;
import PDAO.Controldor.Controlador;
import PDAO.Controldor.ControladorMesero;
import PDAO.Controldor.ControladorPedido;
import PDAO.Controldor.ControladorUser;
import PDAO.Modelo.Mesero;
import PDAO.Modelo.Modelo;
import PDAO.Modelo.factura;
import PDAO.Modelo.productos_Vendido;
import java.awt.Dimension;
import java.sql.Date;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author nahs1
 */
public class Ventana_Opciones extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_Opciones
     */
    String tipo;
     java.sql.Date date2,data;
     public static ArrayList<productos_Vendido> pedidos=new ArrayList<productos_Vendido>();
     ControladoEstadistica ce=new ControladoEstadistica();
    ControladorUser x=new ControladorUser();
    ControladorMesero y=new ControladorMesero();
    ControladorPedido p=new ControladorPedido();
    Controlador z=new Controlador();
    public Ventana_Opciones() {
        initComponents();
        uno.setText(String.valueOf(codigo));
        dos.setText(mesa);
        MesaNumero.setText(mesa);
        MeseroNombre.setText(String.valueOf(codigo));
        jTextField7.setText(String.valueOf((int)(Math.random()*1000)));
        tipo=cargo;
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        if(cargo.equalsIgnoreCase("administrador")){
            JBtnMenu.setEnabled(true);
            JBtnEstadisticas.setEnabled(true);
            JBtnInfMeseros.setEnabled(true);
        }else if(cargo.equalsIgnoreCase("mesero")){
               JBtnMenu.setEnabled(true);
            JBtnEstadisticas.setEnabled(false);
            JBtnInfMeseros.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        uno = new javax.swing.JLabel();
        dos = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        tablita1 = new javax.swing.JTable();
        consult = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel51 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablita = new javax.swing.JTable();
        jTextField6 = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Factura = new javax.swing.JDialog();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        TablaFactura = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        JBtnRetroceder = new javax.swing.JButton();
        infoFact = new javax.swing.JLabel();
        JLblTituloFact = new javax.swing.JLabel();
        JLblPais = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jTextField40 = new javax.swing.JLabel();
        MeseroNombre = new javax.swing.JLabel();
        MesaNumero = new javax.swing.JLabel();
        JLblNotaHorario = new javax.swing.JLabel();
        JLblNota1 = new javax.swing.JLabel();
        JLblIva = new javax.swing.JLabel();
        JLblTotal = new javax.swing.JLabel();
        JLblIvaRes = new javax.swing.JLabel();
        JLblPropinaRes = new javax.swing.JLabel();
        JBtnImprimir = new javax.swing.JButton();
        JLblImagen = new javax.swing.JLabel();
        JLblInforNum = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel40 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        Estadistica = new javax.swing.JFrame();
        JPanelEstadisticas = new javax.swing.JPanel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        JBtnNumVentas = new javax.swing.JButton();
        JBtnPlatoMasVend = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel44 = new javax.swing.JLabel();
        Mesero = new javax.swing.JFrame();
        JPanelMesero = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        JLblNombreMesero2 = new javax.swing.JLabel();
        JTxtUsuario = new javax.swing.JTextField();
        JPassword = new javax.swing.JTextField();
        JLblNombreMesero1 = new javax.swing.JLabel();
        JLblNombreMesero = new javax.swing.JLabel();
        JLblAsignacionMesa = new javax.swing.JLabel();
        JLblNumIden = new javax.swing.JLabel();
        JtxtNombre = new javax.swing.JTextField();
        jTxtNumIde = new javax.swing.JTextField();
        JbtnGuardar = new javax.swing.JButton();
        JBtnAtras = new javax.swing.JButton();
        JLblTitulo = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        JLblFondoMesero = new javax.swing.JLabel();
        ResumenVentas = new javax.swing.JDialog();
        jPanel14 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listMesas = new javax.swing.JList<>();
        jLabel43 = new javax.swing.JLabel();
        jButton28 = new javax.swing.JButton();
        jLabel45 = new javax.swing.JLabel();
        MejorPlato = new javax.swing.JDialog();
        jPanel13 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        fotoplato = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        JBtnMenu = new javax.swing.JButton();
        JBtnFactura = new javax.swing.JButton();
        JBtnInfMeseros = new javax.swing.JButton();
        JBtnSalir = new javax.swing.JButton();
        JBtnEstadisticas = new javax.swing.JButton();
        JLblFondoVOpc = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        jPanel2.setLayout(null);

        jLabel53.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setText("MESA:");
        jPanel2.add(jLabel53);
        jLabel53.setBounds(750, 530, 170, 17);

        jLabel52.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setText("#PEDIDO :");
        jPanel2.add(jLabel52);
        jLabel52.setBounds(750, 70, 90, 17);

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("NUMERO DE MESERO:");
        jPanel2.add(jLabel41);
        jLabel41.setBounds(750, 500, 170, 17);

        uno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        uno.setForeground(new java.awt.Color(255, 255, 255));
        uno.setText("--------");
        jPanel2.add(uno);
        uno.setBounds(930, 500, 50, 17);

        dos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dos.setForeground(new java.awt.Color(255, 255, 255));
        dos.setText("--------");
        jPanel2.add(dos);
        dos.setBounds(930, 530, 50, 17);

        jTextField7.setEditable(false);
        jPanel2.add(jTextField7);
        jTextField7.setBounds(860, 60, 70, 30);

        tablita1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PRODUCTO", "PRECIO_U", "CANTIDAD", "TOTAL"
            }
        ));
        jScrollPane6.setViewportView(tablita1);

        jPanel2.add(jScrollPane6);
        jScrollPane6.setBounds(750, 250, 340, 230);

        consult.setText("Consultar");
        consult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultActionPerformed(evt);
            }
        });
        jPanel2.add(consult);
        consult.setBounds(1000, 100, 90, 23);

        jButton4.setText("INGRESAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(990, 200, 100, 23);

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 1000, 1));
        jPanel2.add(jSpinner1);
        jSpinner1.setBounds(860, 200, 60, 30);

        jLabel51.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("CANTIDAD :");
        jPanel2.add(jLabel51);
        jLabel51.setBounds(750, 210, 90, 17);

        tablita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "PRODUCTO", "PRECIO", "STOCK"
            }
        ));
        jScrollPane4.setViewportView(tablita);

        jPanel2.add(jScrollPane4);
        jScrollPane4.setBounds(750, 140, 340, 40);
        jPanel2.add(jTextField6);
        jTextField6.setBounds(860, 100, 120, 20);

        jLabel50.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setText("PEDIDO");
        jPanel2.add(jLabel50);
        jLabel50.setBounds(830, 0, 220, 50);

        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("PRODUCTO:");
        jPanel2.add(jLabel49);
        jLabel49.setBounds(750, 100, 90, 17);

        jLabel3.setFont(new java.awt.Font("Perpetua Titling MT", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PROMOCIóN");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(80, 10, 180, 30);

        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Promocion.png"))); // NOI18N
        jPanel2.add(jLabel35);
        jLabel35.setBounds(30, 40, 260, 210);

        jLabel31.setFont(new java.awt.Font("Bookman Old Style", 3, 24)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("BOLÓN Boulevard  -  $5,65");
        jLabel31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel31MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel31);
        jLabel31.setBounds(0, 260, 331, 29);

        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Bolón con: Queso, chicharron, dos huevos, tocino,");
        jPanel2.add(jLabel30);
        jLabel30.setBounds(0, 300, 243, 14);

        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("queso rayado, maduro, mortadela.");
        jPanel2.add(jLabel33);
        jLabel33.setBounds(0, 320, 168, 14);

        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Jugo de mora, leche, cafe, chifles y frutas secas.");
        jPanel2.add(jLabel34);
        jLabel34.setBounds(0, 340, 237, 14);

        jLabel5.setFont(new java.awt.Font("Bookman Old Style", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Desayuno Criollo  -  $4,50");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(350, 70, 323, 29);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Café, leche, jugo de naranja, pan,");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(360, 110, 167, 14);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("mantequilla, dos huevos al gusto,");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(360, 130, 161, 14);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Gallo pinto, maduro y queso frito.");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(360, 150, 161, 14);

        jLabel9.setFont(new java.awt.Font("Bookman Old Style", 3, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Desayuno Americano  -  $3,75");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(350, 190, 372, 29);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Café, leche, jugo de naranja, pan");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(360, 230, 163, 14);

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("cake con miel (opcional) y ");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(360, 250, 125, 14);

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("frutas disponibles en temporada");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(360, 270, 154, 14);

        jLabel13.setFont(new java.awt.Font("Bookman Old Style", 3, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Continental  -  $4,00");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(350, 300, 259, 29);

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Tostadas francesas, huevo revuelto,");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(360, 340, 178, 14);

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("jugo de naranja, frutas frescas,");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(360, 360, 154, 14);

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("mantequilla, miel, café y leche.");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(360, 380, 148, 14);

        jLabel17.setFont(new java.awt.Font("Bookman Old Style", 3, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Desayuno Boulevard  -  $5,00");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(350, 410, 365, 29);

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Omelette de huevo con Jamón y queso,");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(360, 450, 191, 14);

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("frijoles fritos o molidos, crema y");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(360, 470, 152, 14);

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("tostadas americanas con mantequilla,");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(360, 490, 180, 14);

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("café, leche y jugo de naranja.");
        jPanel2.add(jLabel21);
        jLabel21.setBounds(360, 510, 145, 14);

        jLabel22.setFont(new java.awt.Font("Bookman Old Style", 3, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("EXTRAS");
        jPanel2.add(jLabel22);
        jLabel22.setBounds(100, 360, 104, 40);

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Café con leche-- $1,50");
        jPanel2.add(jLabel23);
        jLabel23.setBounds(0, 400, 120, 20);

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Agua------------- $0,75");
        jPanel2.add(jLabel24);
        jLabel24.setBounds(0, 430, 120, 20);

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Café negro----- $1,00");
        jPanel2.add(jLabel25);
        jLabel25.setBounds(0, 460, 120, 20);

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Cola------------- $1,25");
        jPanel2.add(jLabel26);
        jLabel26.setBounds(0, 550, 110, 20);

        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Chifles-----------$0,50");
        jPanel2.add(jLabel27);
        jLabel27.setBounds(0, 520, 110, 20);

        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Huevo frito-----------------------$0,70");
        jPanel2.add(jLabel28);
        jLabel28.setBounds(140, 400, 180, 20);

        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Tocino----------- $0,80");
        jPanel2.add(jLabel36);
        jLabel36.setBounds(0, 490, 110, 20);

        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Papa rellena--------------------- $1,50");
        jPanel2.add(jLabel38);
        jLabel38.setBounds(140, 430, 180, 20);

        jLabel42.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("MENÚ");
        jPanel2.add(jLabel42);
        jLabel42.setBounds(420, 0, 170, 50);

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(10, 570, 80, 30);

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButton2.setText("Generar Pedido");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(960, 570, 130, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/0c2c2d09-4a55-4c1b-8755-4fe8730d9a58.png"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 0, 1110, 610);

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu.getContentPane());
        Menu.getContentPane().setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1107, Short.MAX_VALUE)
                .addContainerGap())
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
        );

        Factura.setTitle("FACTURA");
        Factura.setMinimumSize(new java.awt.Dimension(680, 694));
        Factura.setModal(true);
        Factura.setResizable(false);
        Factura.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel10.setMaximumSize(new java.awt.Dimension(620, 400));
        jPanel10.setMinimumSize(new java.awt.Dimension(620, 400));
        jPanel10.setLayout(null);

        TablaFactura.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TablaFactura.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        TablaFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "         PRODUCTO", "            PRECIO", "         CANTIDAD", "         SUBTOTAL"
            }
        ));
        jScrollPane5.setViewportView(TablaFactura);

        jPanel10.add(jScrollPane5);
        jScrollPane5.setBounds(50, 330, 590, 150);

        jPanel11.setBackground(new java.awt.Color(204, 204, 204));
        jPanel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null));
        jPanel11.setLayout(null);

        jLabel32.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel32.setText("Teléfono:");
        jPanel11.add(jLabel32);
        jLabel32.setBounds(10, 70, 90, 20);

        jLabel37.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel37.setText("Cedula:");
        jPanel11.add(jLabel37);
        jLabel37.setBounds(10, 44, 90, 20);

        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel29.setText("Nombre Cliente:");
        jPanel11.add(jLabel29);
        jLabel29.setBounds(10, 14, 90, 20);
        jPanel11.add(jTextField1);
        jTextField1.setBounds(110, 70, 160, 20);
        jPanel11.add(jTextField2);
        jTextField2.setBounds(110, 40, 160, 20);
        jPanel11.add(jTextField3);
        jTextField3.setBounds(110, 10, 160, 20);

        jPanel10.add(jPanel11);
        jPanel11.setBounds(330, 130, 310, 110);

        JBtnRetroceder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Retroceder.png"))); // NOI18N
        JBtnRetroceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnRetrocederActionPerformed(evt);
            }
        });
        jPanel10.add(JBtnRetroceder);
        JBtnRetroceder.setBounds(40, 590, 60, 60);

        infoFact.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        infoFact.setText("  Atendido por:");
        infoFact.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10.add(infoFact);
        infoFact.setBounds(330, 290, 110, 30);

        JLblTituloFact.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        JLblTituloFact.setText("                    FACTURA");
        jPanel10.add(JLblTituloFact);
        JLblTituloFact.setBounds(320, 30, 340, 50);

        JLblPais.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        JLblPais.setText("         Ecuador - Guayaquil");
        jPanel10.add(JLblPais);
        JLblPais.setBounds(400, 70, 200, 30);

        jLabel39.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel39.setText("FECHA :");
        jLabel39.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10.add(jLabel39);
        jLabel39.setBounds(330, 250, 110, 30);

        jTextField40.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField40.setText("    Mesa N°: ");
        jTextField40.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10.add(jTextField40);
        jTextField40.setBounds(50, 290, 90, 30);

        MeseroNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MeseroNombre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10.add(MeseroNombre);
        MeseroNombre.setBounds(460, 290, 180, 30);

        MesaNumero.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MesaNumero.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10.add(MesaNumero);
        MesaNumero.setBounds(150, 290, 60, 30);

        JLblNotaHorario.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        JLblNotaHorario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLblNotaHorario.setText("Lunes a Sábado 7:00 am a 12:00 pm");
        jPanel10.add(JLblNotaHorario);
        JLblNotaHorario.setBounds(60, 540, 240, 60);

        JLblNota1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        JLblNota1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLblNota1.setText("HORARIO DE ATENCIÓN");
        jPanel10.add(JLblNota1);
        JLblNota1.setBounds(90, 530, 170, 17);

        JLblIva.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        JLblIva.setText("+IVA");
        jPanel10.add(JLblIva);
        JLblIva.setBounds(430, 500, 100, 20);

        JLblTotal.setFont(new java.awt.Font("Courier New", 3, 12)); // NOI18N
        JLblTotal.setText("TOTAL");
        jPanel10.add(JLblTotal);
        JLblTotal.setBounds(430, 530, 90, 20);

        JLblIvaRes.setFont(new java.awt.Font("Courier New", 0, 11)); // NOI18N
        JLblIvaRes.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel10.add(JLblIvaRes);
        JLblIvaRes.setBounds(540, 500, 90, 20);

        JLblPropinaRes.setFont(new java.awt.Font("Courier New", 0, 11)); // NOI18N
        JLblPropinaRes.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel10.add(JLblPropinaRes);
        JLblPropinaRes.setBounds(530, 530, 100, 20);

        JBtnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imprimir.png"))); // NOI18N
        JBtnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnImprimirActionPerformed(evt);
            }
        });
        jPanel10.add(JBtnImprimir);
        JBtnImprimir.setBounds(570, 590, 60, 60);

        JLblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Factura.png"))); // NOI18N
        jPanel10.add(JLblImagen);
        JLblImagen.setBounds(0, 60, 400, 200);

        JLblInforNum.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        JLblInforNum.setText(" Teléfono:  2 421314");
        jPanel10.add(JLblInforNum);
        JLblInforNum.setBounds(440, 100, 130, 20);
        jPanel10.add(jDateChooser1);
        jDateChooser1.setBounds(460, 250, 180, 30);

        jLabel40.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel40.setText("       Factura:   ");
        jLabel40.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10.add(jLabel40);
        jLabel40.setBounds(50, 250, 110, 30);

        jLabel54.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel54.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10.add(jLabel54);
        jLabel54.setBounds(160, 250, 110, 30);

        Factura.getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 710));

        Estadistica.setTitle("Ventana_Estadisticas");
        Estadistica.setMinimumSize(new java.awt.Dimension(505, 428));
        Estadistica.setResizable(false);

        JPanelEstadisticas.setForeground(new java.awt.Color(255, 255, 255));
        JPanelEstadisticas.setLayout(null);
        JPanelEstadisticas.add(jDateChooser2);
        jDateChooser2.setBounds(20, 140, 180, 30);

        JBtnNumVentas.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        JBtnNumVentas.setForeground(new java.awt.Color(255, 255, 255));
        JBtnNumVentas.setText("         Ventas Realizadas Un Dia");
        JBtnNumVentas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        JBtnNumVentas.setContentAreaFilled(false);
        JBtnNumVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JBtnNumVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnNumVentasActionPerformed(evt);
            }
        });
        JPanelEstadisticas.add(JBtnNumVentas);
        JBtnNumVentas.setBounds(240, 140, 230, 40);

        JBtnPlatoMasVend.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        JBtnPlatoMasVend.setForeground(new java.awt.Color(255, 255, 255));
        JBtnPlatoMasVend.setText("Ventas Totales");
        JBtnPlatoMasVend.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        JBtnPlatoMasVend.setContentAreaFilled(false);
        JBtnPlatoMasVend.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JBtnPlatoMasVend.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JBtnPlatoMasVend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnPlatoMasVendActionPerformed(evt);
            }
        });
        JPanelEstadisticas.add(JBtnPlatoMasVend);
        JBtnPlatoMasVend.setBounds(240, 270, 240, 40);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("       Estadísticas");
        JPanelEstadisticas.add(jLabel4);
        jLabel4.setBounds(120, 60, 260, 40);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Retroceder.png"))); // NOI18N
        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        JPanelEstadisticas.add(jButton3);
        jButton3.setBounds(420, 20, 58, 60);

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo2.1.png"))); // NOI18N
        JPanelEstadisticas.add(jLabel44);
        jLabel44.setBounds(0, 0, 560, 430);

        javax.swing.GroupLayout EstadisticaLayout = new javax.swing.GroupLayout(Estadistica.getContentPane());
        Estadistica.getContentPane().setLayout(EstadisticaLayout);
        EstadisticaLayout.setHorizontalGroup(
            EstadisticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelEstadisticas, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
        );
        EstadisticaLayout.setVerticalGroup(
            EstadisticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EstadisticaLayout.createSequentialGroup()
                .addComponent(JPanelEstadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Mesero.setTitle("Informacion_Mesero");
        Mesero.setMinimumSize(new java.awt.Dimension(544, 481));
        Mesero.setResizable(false);

        JPanelMesero.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cedula :");
        jLabel1.setOpaque(true);
        JPanelMesero.add(jLabel1);
        jLabel1.setBounds(140, 360, 80, 30);
        JPanelMesero.add(jTextField5);
        jTextField5.setBounds(280, 360, 130, 30);

        JLblNombreMesero2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        JLblNombreMesero2.setText("usuario:");
        JPanelMesero.add(JLblNombreMesero2);
        JLblNombreMesero2.setBounds(120, 100, 60, 20);

        JTxtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTxtUsuarioActionPerformed(evt);
            }
        });
        JPanelMesero.add(JTxtUsuario);
        JTxtUsuario.setBounds(290, 100, 120, 20);
        JPanelMesero.add(JPassword);
        JPassword.setBounds(290, 130, 120, 20);

        JLblNombreMesero1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        JLblNombreMesero1.setText("contraseña:");
        JPanelMesero.add(JLblNombreMesero1);
        JLblNombreMesero1.setBounds(120, 130, 100, 20);

        JLblNombreMesero.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        JLblNombreMesero.setText("Nombres: ");
        JPanelMesero.add(JLblNombreMesero);
        JLblNombreMesero.setBounds(120, 70, 70, 20);

        JLblAsignacionMesa.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        JLblAsignacionMesa.setText("Asignacion de mesas: ");
        JPanelMesero.add(JLblAsignacionMesa);
        JLblAsignacionMesa.setBounds(120, 170, 180, 17);

        JLblNumIden.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        JLblNumIden.setText("Cedula");
        JPanelMesero.add(JLblNumIden);
        JLblNumIden.setBounds(120, 40, 160, 20);
        JPanelMesero.add(JtxtNombre);
        JtxtNombre.setBounds(290, 70, 120, 20);
        JPanelMesero.add(jTxtNumIde);
        jTxtNumIde.setBounds(290, 40, 120, 20);

        JbtnGuardar.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        JbtnGuardar.setText("Ingresar");
        JbtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnGuardarActionPerformed(evt);
            }
        });
        JPanelMesero.add(JbtnGuardar);
        JbtnGuardar.setBounds(320, 200, 90, 30);

        JBtnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Retroceder.png"))); // NOI18N
        JBtnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnAtrasActionPerformed(evt);
            }
        });
        JPanelMesero.add(JBtnAtras);
        JBtnAtras.setBounds(10, 20, 60, 60);

        JLblTitulo.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        JLblTitulo.setText("     Información del Personal");
        JPanelMesero.add(JLblTitulo);
        JLblTitulo.setBounds(110, 0, 310, 50);
        JPanelMesero.add(jTextField4);
        jTextField4.setBounds(290, 170, 120, 20);

        jButton5.setText("Actualizar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        JPanelMesero.add(jButton5);
        jButton5.setBounds(120, 200, 90, 30);

        jButton6.setText("Eliminar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        JPanelMesero.add(jButton6);
        jButton6.setBounds(280, 410, 90, 30);

        jButton7.setText("Consultar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        JPanelMesero.add(jButton7);
        jButton7.setBounds(140, 410, 90, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N° Identificacion", "Nombre", "N° Mesero", "N° Mesa", "usuario", "contraseña"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        JPanelMesero.add(jScrollPane3);
        jScrollPane3.setBounds(2, 240, 530, 110);

        JLblFondoMesero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo1.png"))); // NOI18N
        JPanelMesero.add(JLblFondoMesero);
        JLblFondoMesero.setBounds(0, -10, 550, 540);

        javax.swing.GroupLayout MeseroLayout = new javax.swing.GroupLayout(Mesero.getContentPane());
        Mesero.getContentPane().setLayout(MeseroLayout);
        MeseroLayout.setHorizontalGroup(
            MeseroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelMesero, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
        );
        MeseroLayout.setVerticalGroup(
            MeseroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelMesero, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        ResumenVentas.setTitle("Resumen_Ventas");
        ResumenVentas.setMinimumSize(new java.awt.Dimension(451, 377));
        ResumenVentas.setResizable(false);

        jPanel14.setForeground(new java.awt.Color(204, 204, 204));
        jPanel14.setLayout(null);

        listMesas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        listMesas.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        listMesas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Mesa 1", "Mesa 2", "Mesa 3", "Mesa 4", "Mesa 5", "Mesa 6", "Mesa 7", "Mesa 8", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listMesas.setSelectionBackground(new java.awt.Color(102, 153, 0));
        jScrollPane1.setViewportView(listMesas);

        jPanel14.add(jScrollPane1);
        jScrollPane1.setBounds(100, 70, 270, 210);

        jLabel43.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("      Resumen de Ventas");
        jPanel14.add(jLabel43);
        jLabel43.setBounds(100, 40, 270, 28);

        jButton28.setBackground(java.awt.Color.white);
        jButton28.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton28.setText("VER VENTAS");
        jButton28.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel14.add(jButton28);
        jButton28.setBounds(180, 300, 120, 40);

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo4.png"))); // NOI18N
        jPanel14.add(jLabel45);
        jLabel45.setBounds(0, 0, 470, 380);

        javax.swing.GroupLayout ResumenVentasLayout = new javax.swing.GroupLayout(ResumenVentas.getContentPane());
        ResumenVentas.getContentPane().setLayout(ResumenVentasLayout);
        ResumenVentasLayout.setHorizontalGroup(
            ResumenVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
        );
        ResumenVentasLayout.setVerticalGroup(
            ResumenVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
        );

        MejorPlato.setTitle("Platillo_Favorito");
        MejorPlato.setMinimumSize(new java.awt.Dimension(547, 301));
        MejorPlato.setResizable(false);

        jPanel13.setLayout(null);

        jLabel46.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setText("Platillo del Día");
        jLabel46.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel46.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel13.add(jLabel46);
        jLabel46.setBounds(200, 40, 320, 70);

        fotoplato.setForeground(new java.awt.Color(255, 255, 255));
        fotoplato.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        fotoplato.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel13.add(fotoplato);
        fotoplato.setBounds(220, 140, 290, 60);

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Primero.png"))); // NOI18N
        jPanel13.add(jLabel47);
        jLabel47.setBounds(30, 80, 150, 150);

        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Platillo.png"))); // NOI18N
        jPanel13.add(jLabel48);
        jLabel48.setBounds(0, 0, 550, 300);

        javax.swing.GroupLayout MejorPlatoLayout = new javax.swing.GroupLayout(MejorPlato.getContentPane());
        MejorPlato.getContentPane().setLayout(MejorPlatoLayout);
        MejorPlatoLayout.setHorizontalGroup(
            MejorPlatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
        );
        MejorPlatoLayout.setVerticalGroup(
            MejorPlatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventana_Opciones");

        jPanel1.setLayout(null);

        JBtnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu.png"))); // NOI18N
        JBtnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnMenuActionPerformed(evt);
            }
        });
        jPanel1.add(JBtnMenu);
        JBtnMenu.setBounds(110, 60, 110, 100);

        JBtnFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnFacturaActionPerformed(evt);
            }
        });
        jPanel1.add(JBtnFactura);
        JBtnFactura.setBounds(300, 220, 100, 100);

        JBtnInfMeseros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imagen1.png"))); // NOI18N
        JBtnInfMeseros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnInfMeserosActionPerformed(evt);
            }
        });
        jPanel1.add(JBtnInfMeseros);
        JBtnInfMeseros.setBounds(110, 220, 110, 100);

        JBtnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Retroceder.png"))); // NOI18N
        JBtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(JBtnSalir);
        JBtnSalir.setBounds(10, 10, 60, 60);

        JBtnEstadisticas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/estadistica.png"))); // NOI18N
        JBtnEstadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnEstadisticasActionPerformed(evt);
            }
        });
        jPanel1.add(JBtnEstadisticas);
        JBtnEstadisticas.setBounds(300, 60, 110, 100);

        JLblFondoVOpc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo5.png"))); // NOI18N
        jPanel1.add(JLblFondoVOpc);
        JLblFondoVOpc.setBounds(0, 0, 540, 440);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnSalirActionPerformed
        // Botón de Retroceder en Ventana Opcion
        Ventana_Ingreso vi = new Ventana_Ingreso();
        vi.setVisible(true);
        vi.JTxtUsuario.setText("");
        vi.JPassword.setText("");
        this.dispose();
        
    }//GEN-LAST:event_JBtnSalirActionPerformed

    private void JBtnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnMenuActionPerformed
        // Botón de Ventana Opcion
        Menu.setVisible(true);
        Menu.setSize(new Dimension(1290, 650));
        this.dispose();
        
    }//GEN-LAST:event_JBtnMenuActionPerformed

    private void JBtnEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnEstadisticasActionPerformed
        // Botón de Ventana Opcion
        Estadistica.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_JBtnEstadisticasActionPerformed

    private void JBtnInfMeserosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnInfMeserosActionPerformed
        // Botón de Ventana Opcion
        Mesero.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_JBtnInfMeserosActionPerformed

    private void JBtnFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnFacturaActionPerformed
        // Botón de Ventana Opcion
        Factura.setVisible(true);
        
    }//GEN-LAST:event_JBtnFacturaActionPerformed

    private void JBtnRetrocederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnRetrocederActionPerformed
         //Boton retrocede en Factura
        Factura.setVisible(false);
        this.setVisible(true);
         
    }//GEN-LAST:event_JBtnRetrocederActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Boton retrocede en Menu
        Menu.setVisible(false);
        this.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Ventana Menu a Ventana Pedido
        Menu.dispose();
        z.llenar_Array(tablita1, jTextField7.getText(),pedidos,TablaFactura,jLabel54,JLblIvaRes,JLblPropinaRes);
        System.out.println(pedidos.size());
        Factura.setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Retrocede en Estadisticas
        Estadistica.dispose();
        this.setVisible(true);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void JBtnPlatoMasVendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnPlatoMasVendActionPerformed
    ce.todos();        // Ventana Estadistica a Ventana Platillo Favorito
    }//GEN-LAST:event_JBtnPlatoMasVendActionPerformed

    private void JBtnNumVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnNumVentasActionPerformed
       data=new java.sql.Date(jDateChooser2.getDate().getTime());
        ce.dia(data);
    }//GEN-LAST:event_JBtnNumVentasActionPerformed

    private void JBtnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnAtrasActionPerformed

        Mesero.dispose();
        this.setVisible(true);
        
    }//GEN-LAST:event_JBtnAtrasActionPerformed

    private void JbtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnGuardarActionPerformed
        Modelo usuario= new Modelo(JTxtUsuario.getText(), JPassword.getText(),"Mesero");
        x.registrar(usuario); 
        Mesero mesero=new Mesero(jTxtNumIde.getText(),JtxtNombre.getText(),jTextField4.getText(),codigo);
        y.registrar(mesero);
        z.tabla_personal(jTable1, usuario, mesero,id);
    }//GEN-LAST:event_JbtnGuardarActionPerformed

    private void JTxtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTxtUsuarioActionPerformed

    }//GEN-LAST:event_JTxtUsuarioActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Modelo usuario= new Modelo(JTxtUsuario.getText(), JPassword.getText(),"Mesero");
        Mesero mesero=new Mesero(jTxtNumIde.getText(),JtxtNombre.getText(),jTextField4.getText());
        y.actualizar(mesero);
        x.actualizar(usuario);
        z.tabla_personal(jTable1, usuario, mesero,id);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        y.consultar(jTextField5.getText(),jTable1);
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       y.eliminar(jTextField5.getText());
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jLabel31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseClicked
    JOptionPane.showMessageDialog(null, "BOLON BOULEVARD");
    }//GEN-LAST:event_jLabel31MouseClicked

    private void consultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultActionPerformed
    p.consultar(jTextField6.getText(), tablita);
    }//GEN-LAST:event_consultActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
     p.llenar_tabla(nom,pre,(int)jSpinner1.getValue(), tablita1);   // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void JBtnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnImprimirActionPerformed
        date2=new java.sql.Date(jDateChooser1.getDate().getTime());
        System.out.println(date2);
        z.facturacion(new factura(jTextField3.getText(), jTextField2.getText(),jTextField1.getText(), jLabel54.getText(), MesaNumero.getText(), MeseroNombre.getText(), JLblPropinaRes.getText()),date2);        // TODO add your handling code here:
    }//GEN-LAST:event_JBtnImprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Opciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame Estadistica;
    private javax.swing.JDialog Factura;
    private javax.swing.JButton JBtnAtras;
    public javax.swing.JButton JBtnEstadisticas;
    public javax.swing.JButton JBtnFactura;
    private javax.swing.JButton JBtnImprimir;
    public javax.swing.JButton JBtnInfMeseros;
    public javax.swing.JButton JBtnMenu;
    private javax.swing.JButton JBtnNumVentas;
    private javax.swing.JButton JBtnPlatoMasVend;
    private javax.swing.JButton JBtnRetroceder;
    private javax.swing.JButton JBtnSalir;
    private javax.swing.JLabel JLblAsignacionMesa;
    private javax.swing.JLabel JLblFondoMesero;
    private javax.swing.JLabel JLblFondoVOpc;
    private javax.swing.JLabel JLblImagen;
    private javax.swing.JLabel JLblInforNum;
    private javax.swing.JLabel JLblIva;
    private javax.swing.JLabel JLblIvaRes;
    private javax.swing.JLabel JLblNombreMesero;
    private javax.swing.JLabel JLblNombreMesero1;
    private javax.swing.JLabel JLblNombreMesero2;
    private javax.swing.JLabel JLblNota1;
    private javax.swing.JLabel JLblNotaHorario;
    private javax.swing.JLabel JLblNumIden;
    private javax.swing.JLabel JLblPais;
    private javax.swing.JLabel JLblPropinaRes;
    private javax.swing.JLabel JLblTitulo;
    private javax.swing.JLabel JLblTituloFact;
    private javax.swing.JLabel JLblTotal;
    private javax.swing.JPanel JPanelEstadisticas;
    private javax.swing.JPanel JPanelMesero;
    private javax.swing.JTextField JPassword;
    private javax.swing.JTextField JTxtUsuario;
    private javax.swing.JButton JbtnGuardar;
    private javax.swing.JTextField JtxtNombre;
    private javax.swing.JDialog MejorPlato;
    private javax.swing.JFrame Menu;
    private javax.swing.JLabel MesaNumero;
    private javax.swing.JFrame Mesero;
    private javax.swing.JLabel MeseroNombre;
    private javax.swing.JDialog ResumenVentas;
    private javax.swing.JTable TablaFactura;
    private javax.swing.JButton consult;
    private javax.swing.JLabel dos;
    private javax.swing.JLabel fotoplato;
    private javax.swing.JLabel infoFact;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel jTextField40;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTxtNumIde;
    private javax.swing.JList<String> listMesas;
    private javax.swing.JTable tablita;
    private javax.swing.JTable tablita1;
    private javax.swing.JLabel uno;
    // End of variables declaration//GEN-END:variables
}
